# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-11 06:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_number', models.IntegerField()),
                ('img_1', models.ImageField(default=b'images/level1.jpg', upload_to=b'images')),
                ('img_2', models.ImageField(default=b'images/level1.jpg', upload_to=b'images')),
                ('img_3', models.ImageField(default=b'images/level1.jpg', upload_to=b'images')),
                ('img_4', models.ImageField(default=b'images/level1.jpg', upload_to=b'images')),
                ('text', models.TextField()),
                ('answer', models.CharField(max_length=200)),
                ('numuser', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('wrong', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Notif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name=datetime.datetime(2018, 2, 11, 6, 27, 56, 611120))),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
